<a href="https://colab.research.google.com/github/davacam/Inteligencia_Artificial/blob/main/SEGUNDO_CORTE/TALLER_PANDA_PD%232/Tallerpanda2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. CREACIÓN Y EXPLORACIÓN DEL DATAFRAME**

In [1]:
# IMPORTANDO LAS LIBRERÍAS PARA LA MANIPULACIÓN DE LOS DATOS
import pandas as pd
import numpy as np

In [28]:
#IMPORTANDO EL DATASET BASE, ARCHIVO EXCEL DESDE EL GITHUB, REALIZANDO LA LECTURA DEL MISMO Y VISUALIZACIÓN DATAFRAME

url = "https://raw.githubusercontent.com/davacam/Inteligencia_Artificial/main/SEGUNDO_CORTE/TALLER_PANDA_PD%232/productos%20tecnologicos%20IA_panda.xlsx"

df = pd.read_excel(url)
df

                Producto   Precio  Cantidad  Costo_Envio   Categoria
0                 Laptop  3500000         4        50000  Tecnología
1                  Mouse    80000        15        10000  Tecnología
2                Teclado   120000        10        12000  Tecnología
3                  Silla   450000         5        30000     Oficina
4             Escritorio   900000         3        40000     Oficina
5                Monitor  1100000         6        35000  Tecnología
6              Impresora  3734353        22        37566  Tecnología
7                 Tablet  2681051        13        53949  Tecnología
8             Smartphone  4601946        17        36279  Tecnología
9            Auriculares  1750889         9        38481  Tecnología
10    Parlante Bluetooth  2309169        20         6890  Tecnología
11            Cámara Web  3713573         1        13865  Tecnología
12            Disco Duro  4579762        12        47963  Tecnología
13                   SSD  3274406        18        38406  Tecnología
14           Memoria USB  3576923         7        22243  Tecnología
15                Router  3172466        11        10913  Tecnología
16         Switch de Red  4040046         6        29113  Tecnología
17             Micrófono   130029        18        14935  Tecnología
18       Tarjeta Gráfica  1383204        23        33741  Tecnología
19            Procesador  3244902        11        27816  Tecnología
20            Placa Base  2358917        23        49580  Tecnología
21       Fuente de Poder  3287695        19        50398  Tecnología
22              Gabinete  4139108        12         9989  Tecnología
23        Ventilador RGB  2531818        20        44097  Tecnología
24            Smartwatch  3351818        15        36903  Tecnología
25             Proyector  3181423        14        21788  Tecnología
26               Escáner  2035648        21        13998  Tecnología
27            Cable HDMI  1229664         8        51274  Tecnología
28             Cable USB   229920        10        23770  Tecnología
29        Adaptador WiFi   500699         2        29964  Tecnología
30                   UPS  1535359        19        23322  Tecnología
31  Regulador de Voltaje  2100734        12        21973  Tecnología
32              Servidor  4045100         9        59916  Tecnología
33       Docking Station  2765664         9        47794  Tecnología
34     Lector Biométrico  1849494         9        47698  Tecnología
35         Control Gamer  1789534         1        16205  Tecnología
36           Silla Gamer   582941        21        53321  Tecnología
37       Lámpara LED USB  2112354         7        30643  Tecnología
38                 Drone  1272450         1        26647  Tecnología
39            VR Headset   956976        22         6177  Tecnología
40               Mini PC  1614860        14        26659  Tecnología
41                   NAS  4038704        11        30575  Tecnología
42          Impresora 3D  4406357         6        27770  Tecnología
43               Plotter  1341840         5        27119  Tecnología
44       Pantalla Táctil  3454358        14        35500  Tecnología
45      Teclado Mecánico   902916        21        56845  Tecnología
46           Mouse Gamer  2256585         9        59127  Tecnología
47     Capturadora Video  3108174        17        49262  Tecnología
48               Hub USB  3322553         8        37193  Tecnología
49  Cargador Inalámbrico  2822977        13        16026  Tecnología
50            Power Bank   402998        11        20674  Tecnología
51              Apple TV  2238987        20        55170  Tecnología
52            Chromecast   277883         4        45094  Tecnología
53            Alexa Echo  4612855         7        31979  Tecnología
54           Google Nest   648398         3        58402  Tecnología
55    Sensor Inteligente  2737623        25        51619  Tecnología
56      Cámara Seguridad  1063879        10        48312  Tecnología
57          Kit Domótica  4191797        20        40203  Tecnología
58          Raspberry Pi  4645546        16        12304  Tecnología
59           Arduino Kit   870026         1        35879  Tecnología

In [32]:
#VISUALIZANDO LAS PRIMERAS 5 FILAS DEL DATAFRAME CON EL METODO HEAD
df.head()

     Producto   Precio  Cantidad  Costo_Envio   Categoria
0      Laptop  3500000         4        50000  Tecnología
1       Mouse    80000        15        10000  Tecnología
2     Teclado   120000        10        12000  Tecnología
3       Silla   450000         5        30000     Oficina
4  Escritorio   900000         3        40000     Oficina

In [30]:
#VISUALIZANDO LAS ULTIMAS 10 FILAS DEL DATFRAME CON EL METODO TAIL
df.tail(10)

              Producto   Precio  Cantidad  Costo_Envio   Categoria
50          Power Bank   402998        11        20674  Tecnología
51            Apple TV  2238987        20        55170  Tecnología
52          Chromecast   277883         4        45094  Tecnología
53          Alexa Echo  4612855         7        31979  Tecnología
54         Google Nest   648398         3        58402  Tecnología
55  Sensor Inteligente  2737623        25        51619  Tecnología
56    Cámara Seguridad  1063879        10        48312  Tecnología
57        Kit Domótica  4191797        20        40203  Tecnología
58        Raspberry Pi  4645546        16        12304  Tecnología
59         Arduino Kit   870026         1        35879  Tecnología

In [31]:
print("Últimas 10 filas")
print(df.tail(10))

Últimas 10 filas
              Producto   Precio  Cantidad  Costo_Envio   Categoria
50          Power Bank   402998        11        20674  Tecnología
51            Apple TV  2238987        20        55170  Tecnología
52          Chromecast   277883         4        45094  Tecnología
53          Alexa Echo  4612855         7        31979  Tecnología
54         Google Nest   648398         3        58402  Tecnología
55  Sensor Inteligente  2737623        25        51619  Tecnología
56    Cámara Seguridad  1063879        10        48312  Tecnología
57        Kit Domótica  4191797        20        40203  Tecnología
58        Raspberry Pi  4645546        16        12304  Tecnología
59         Arduino Kit   870026         1        35879  Tecnología

In [47]:
#VISUALIZACION DEL NOMBRE DE LAS COLUMNAS Y SU TIPO DE DATO
df.dtypes

Producto       object
Precio          int64
Cantidad        int64
Costo_Envio     int64
Categoria      object
Total_Venta     int64
Costo_Total     int64
dtype: object

In [33]:
# VISUALIZACION DEL TAMAÑO DEL DATAFRAME CON EL METODO SHAPE. ES DECIR, TOTAL DE FILAS Y COLUMNASdf.shape

(60, 5)

In [44]:
#DESCRIPCION ESTADÍSTICA DE LAS COLUMNAS NUMERICAS DEL DATAFRAME
df.describe()

             Precio   Cantidad   Costo_Envio   Total_Venta   Costo_Total
count  6.000000e+01  60.000000     60.000000  6.000000e+01  6.000000e+01
mean   2.319323e+06  12.000000  33672.150000  2.890949e+07  2.894316e+07
std    1.388081e+06   6.671467  15129.222562  2.338320e+07  2.338510e+07
min    8.000000e+04   1.000000   6177.000000  8.700260e+05  9.059050e+05
25%    1.090970e+06   7.000000  22175.500000  6.681900e+06  6.710989e+06
50%    2.282877e+06  11.000000  34370.500000  2.512363e+07  2.514574e+07
75%    3.377453e+06  18.000000  47836.250000  4.513065e+07  4.517375e+07
max    4.645546e+06  25.000000  59916.000000  8.383594e+07  8.387614e+07

# **2. OPERACIONES MATEMÁTICAS ENTRE COLUMNAS**

In [43]:
df["Total_Venta"] = df["Precio"] * df["Cantidad"]
df.head()

,Producto,Precio,Cantidad,Costo_Envio,Categoria,Total_Venta,Costo_Total
0,Laptop,3500000,4,50000,Tecnología,14000000,14050000
1,Mouse,80000,15,10000,Tecnología,1200000,1210000
2,Teclado,120000,10,12000,Tecnología,1200000,1212000
3,Silla,450000,5,30000,Oficina,2250000,2280000
4,Escritorio,900000,3,40000,Oficina,2700000,2740000

In [41]:
df["Costo_Total"] = df["Total_Venta"] + df["Costo_Envio"]
df.head()

,Producto,Precio,Cantidad,Costo_Envio,Categoria,Total_Venta,Costo_Total
0,Laptop,3500000,4,50000,Tecnología,14000000,14050000
1,Mouse,80000,15,10000,Tecnología,1200000,1210000
2,Teclado,120000,10,12000,Tecnología,1200000,1212000
3,Silla,450000,5,30000,Oficina,2250000,2280000
4,Escritorio,900000,3,40000,Oficina,2700000,2740000

In [52]:
#CALCULO DEL PROMEDIO TOTAL DE VENTAS CON LA MEDIDA CENTRAL MEAN-PROMEDIO
promedio_ventas = df["Total_Venta"].mean()

promedio_ventas

np.float64(28909490.7)

In [12]:
mayor_venta = df.loc[df["Total_Venta"].idxmax()]

print("Producto con mayor Total_Venta")
print(mayor_venta)

Producto con mayor Total_Venta
Producto       Kit Domótica
Precio              4191797
Cantidad                 20
Costo_Envio           40203
Categoria        Tecnología
Total_Venta        83835940
Costo_Total        83876143
Name: 57, dtype: object

In [13]:
menor_venta = df.loc[df["Total_Venta"].idxmin()]

print("Producto con menor Total_Venta")
print(menor_venta)

Producto con menor Total_Venta
Producto       Arduino Kit
Precio              870026
Cantidad                 1
Costo_Envio          35879
Categoria       Tecnología
Total_Venta         870026
Costo_Total         905905
Name: 59, dtype: object

In [14]:
df["IVA"] = df["Total_Venta"] * 0.19

print(df.head())

     Producto   Precio  Cantidad  Costo_Envio   Categoria  Total_Venta  \
0      Laptop  3500000         4        50000  Tecnología     14000000
1       Mouse    80000        15        10000  Tecnología      1200000
2     Teclado   120000        10        12000  Tecnología      1200000
3       Silla   450000         5        30000     Oficina      2250000
4  Escritorio   900000         3        40000     Oficina      2700000

   Costo_Total        IVA
0     14050000  2660000.0
1      1210000   228000.0
2      1212000   228000.0
3      2280000   427500.0
4      2740000   513000.0

In [15]:
df["Ganancia_Estimada"] = df["Total_Venta"] * 0.25

print(df.head())

     Producto   Precio  Cantidad  Costo_Envio   Categoria  Total_Venta  \
0      Laptop  3500000         4        50000  Tecnología     14000000
1       Mouse    80000        15        10000  Tecnología      1200000
2     Teclado   120000        10        12000  Tecnología      1200000
3       Silla   450000         5        30000     Oficina      2250000
4  Escritorio   900000         3        40000     Oficina      2700000

   Costo_Total        IVA  Ganancia_Estimada
0     14050000  2660000.0          3500000.0
1      1210000   228000.0           300000.0
2      1212000   228000.0           300000.0
3      2280000   427500.0           562500.0
4      2740000   513000.0           675000.0

In [16]:
df["Perdida_Estimada"] = df["Total_Venta"] * 0.0005

print(df.head())

     Producto   Precio  Cantidad  Costo_Envio   Categoria  Total_Venta  \
0      Laptop  3500000         4        50000  Tecnología     14000000
1       Mouse    80000        15        10000  Tecnología      1200000
2     Teclado   120000        10        12000  Tecnología      1200000
3       Silla   450000         5        30000     Oficina      2250000
4  Escritorio   900000         3        40000     Oficina      2700000

   Costo_Total        IVA  Ganancia_Estimada  Perdida_Estimada
0     14050000  2660000.0          3500000.0            7000.0
1      1210000   228000.0           300000.0             600.0
2      1212000   228000.0           300000.0             600.0
3      2280000   427500.0           562500.0            1125.0
4      2740000   513000.0           675000.0            1350.0

In [17]:
total_general = df["Total_Venta"].sum()

df["Porcentaje_Ventas"] = (df["Total_Venta"] / total_general) * 100

print(df.head())

     Producto   Precio  Cantidad  Costo_Envio   Categoria  Total_Venta  \
0      Laptop  3500000         4        50000  Tecnología     14000000
1       Mouse    80000        15        10000  Tecnología      1200000
2     Teclado   120000        10        12000  Tecnología      1200000
3       Silla   450000         5        30000     Oficina      2250000
4  Escritorio   900000         3        40000     Oficina      2700000

   Costo_Total        IVA  Ganancia_Estimada  Perdida_Estimada  \
0     14050000  2660000.0          3500000.0            7000.0
1      1210000   228000.0           300000.0             600.0
2      1212000   228000.0           300000.0             600.0
3      2280000   427500.0           562500.0            1125.0
4      2740000   513000.0           675000.0            1350.0

   Porcentaje_Ventas
0           0.807117
1           0.069181
2           0.069181
3           0.129715
4           0.155658

In [18]:
productos_15 = df[df["Porcentaje_Ventas"] > 15]

print("Productos con porcentaje superior al 15%")
print(productos_15)

Productos con porcentaje superior al 15%
Empty DataFrame
Columns: [Producto, Precio, Cantidad, Costo_Envio, Categoria, Total_Venta, Costo_Total, IVA, Ganancia_Estimada, Perdida_Estimada, Porcentaje_Ventas]
Index: []

In [19]:
media_precio = df["Precio"].mean()
mediana_precio = df["Precio"].median()
moda_precio = df["Precio"].mode()

print("Media:", media_precio)
print("Mediana:", mediana_precio)
print("Moda:")
print(moda_precio)

Media: 2319322.5166666666
Mediana: 2282877.0
Moda:
0       80000
1      120000
2      130029
3      229920
4      277883
5      402998
6      450000
7      500699
8      582941
9      648398
10     870026
11     900000
12     902916
13     956976
14    1063879
15    1100000
16    1229664
17    1272450
18    1341840
19    1383204
20    1535359
21    1614860
22    1750889
23    1789534
24    1849494
25    2035648
26    2100734
27    2112354
28    2238987
29    2256585
30    2309169
31    2358917
32    2531818
33    2681051
34    2737623
35    2765664
36    2822977
37    3108174
38    3172466
39    3181423
40    3244902
41    3274406
42    3287695
43    3322553
44    3351818
45    3454358
46    3500000
47    3576923
48    3713573
49    3734353
50    4038704
51    4040046
52    4045100
53    4139108
54    4191797
55    4406357
56    4579762
57    4601946
58    4612855
59    4645546
Name: Precio, dtype: int64

In [20]:
desviacion = df["Cantidad"].std()

print("Desviación estándar:")
print(desviacion)

Desviación estándar:
6.6714671981709674

In [21]:
maximo = df["Total_Venta"].max()
minimo = df["Total_Venta"].min()

print("Valor máximo:", maximo)
print("Valor mínimo:", minimo)

Valor máximo: 83835940
Valor mínimo: 870026

In [22]:
print("""
MEDIA:
Es el promedio de los precios.

MEDIANA:
Es el valor central de los precios.

MODA:
Es el valor que más se repite.

DESVIACIÓN ESTÁNDAR:
Indica qué tan dispersos están los datos respecto al promedio.

VALOR MÁXIMO:
Es la venta más alta registrada.

VALOR MÍNIMO:
Es la venta más baja registrada.
""")

MEDIA:
Es el promedio de los precios.

MEDIANA:
Es el valor central de los precios.

MODA:
Es el valor que más se repite.

DESVIACIÓN ESTÁNDAR:
Indica qué tan dispersos están los datos respecto al promedio.

VALOR MÁXIMO:
Es la venta más alta registrada.

VALOR MÍNIMO:
Es la venta más baja registrada.

In [23]:
tecnologia = df[df["Categoria"] == "Tecnología"]

print(tecnologia)

                Producto   Precio  Cantidad  Costo_Envio   Categoria  \
0                 Laptop  3500000         4        50000  Tecnología
1                  Mouse    80000        15        10000  Tecnología
2                Teclado   120000        10        12000  Tecnología
5                Monitor  1100000         6        35000  Tecnología
6              Impresora  3734353        22        37566  Tecnología
7                 Tablet  2681051        13        53949  Tecnología
8             Smartphone  4601946        17        36279  Tecnología
9            Auriculares  1750889         9        38481  Tecnología
10    Parlante Bluetooth  2309169        20         6890  Tecnología
11            Cámara Web  3713573         1        13865  Tecnología
12            Disco Duro  4579762        12        47963  Tecnología
13                   SSD  3274406        18        38406  Tecnología
14           Memoria USB  3576923         7        22243  Tecnología
15                Router  3172466        11        10913  Tecnología
16         Switch de Red  4040046         6        29113  Tecnología
17             Micrófono   130029        18        14935  Tecnología
18       Tarjeta Gráfica  1383204        23        33741  Tecnología
19            Procesador  3244902        11        27816  Tecnología
20            Placa Base  2358917        23        49580  Tecnología
21       Fuente de Poder  3287695        19        50398  Tecnología
22              Gabinete  4139108        12         9989  Tecnología
23        Ventilador RGB  2531818        20        44097  Tecnología
24            Smartwatch  3351818        15        36903  Tecnología
25             Proyector  3181423        14        21788  Tecnología
26               Escáner  2035648        21        13998  Tecnología
27            Cable HDMI  1229664         8        51274  Tecnología
28             Cable USB   229920        10        23770  Tecnología
29        Adaptador WiFi   500699         2        29964  Tecnología
30                   UPS  1535359        19        23322  Tecnología
31  Regulador de Voltaje  2100734        12        21973  Tecnología
32              Servidor  4045100         9        59916  Tecnología
33       Docking Station  2765664         9        47794  Tecnología
34     Lector Biométrico  1849494         9        47698  Tecnología
35         Control Gamer  1789534         1        16205  Tecnología
36           Silla Gamer   582941        21        53321  Tecnología
37       Lámpara LED USB  2112354         7        30643  Tecnología
38                 Drone  1272450         1        26647  Tecnología
39            VR Headset   956976        22         6177  Tecnología
40               Mini PC  1614860        14        26659  Tecnología
41                   NAS  4038704        11        30575  Tecnología
42          Impresora 3D  4406357         6        27770  Tecnología
43               Plotter  1341840         5        27119  Tecnología
44       Pantalla Táctil  3454358        14        35500  Tecnología
45      Teclado Mecánico   902916        21        56845  Tecnología
46           Mouse Gamer  2256585         9        59127  Tecnología
47     Capturadora Video  3108174        17        49262  Tecnología
48               Hub USB  3322553         8        37193  Tecnología
49  Cargador Inalámbrico  2822977        13        16026  Tecnología
50            Power Bank   402998        11        20674  Tecnología
51              Apple TV  2238987        20        55170  Tecnología
52            Chromecast   277883         4        45094  Tecnología
53            Alexa Echo  4612855         7        31979  Tecnología
54           Google Nest   648398         3        58402  Tecnología
55    Sensor Inteligente  2737623        25        51619  Tecnología
56      Cámara Seguridad  1063879        10        48312  Tecnología
57          Kit Domótica  4191797        20        40203  Tecnología
58          Raspberry Pi  4645546        16        12304  Tecnología
59           Arduino Kit   870026         1        35879  Tecnología

    Total_Venta  Costo_Total          IVA  Ganancia_Estimada  \
0      14000000     14050000   2660000.00         3500000.00
1       1200000      1210000    228000.00          300000.00
2       1200000      1212000    228000.00          300000.00
5       6600000      6635000   1254000.00         1650000.00
6      82155766     82193332  15609595.54        20538941.50
7      34853663     34907612   6622195.97         8713415.75
8      78233082     78269361  14864285.58        19558270.50
9      15758001     15796482   2994020.19         3939500.25
10     46183380     46190270   8774842.20        11545845.00
11      3713573      3727438    705578.87          928393.25
12     54957144     55005107  10441857.36        13739286.00
13     58939308     58977714  11198468.52        14734827.00
14     25038461     25060704   4757307.59         6259615.25
15     34897126     34908039   6630453.94         8724281.50
16     24240276     24269389   4605652.44         6060069.00
17      2340522      2355457    444699.18          585130.50
18     31813692     31847433   6044601.48         7953423.00
19     35693922     35721738   6781845.18         8923480.50
20     54255091     54304671  10308467.29        13563772.75
21     62466205     62516603  11868578.95        15616551.25
22     49669296     49679285   9437166.24        12417324.00
23     50636360     50680457   9620908.40        12659090.00
24     50277270     50314173   9552681.30        12569317.50
25     44539922     44561710   8462585.18        11134980.50
26     42748608     42762606   8122235.52        10687152.00
27      9837312      9888586   1869089.28         2459328.00
28      2299200      2322970    436848.00          574800.00
29      1001398      1031362    190265.62          250349.50
30     29171821     29195143   5542645.99         7292955.25
31     25208808     25230781   4789673.52         6302202.00
32     36405900     36465816   6917121.00         9101475.00
33     24890976     24938770   4729285.44         6222744.00
34     16645446     16693144   3162634.74         4161361.50
35      1789534      1805739    340011.46          447383.50
36     12241761     12295082   2325934.59         3060440.25
37     14786478     14817121   2809430.82         3696619.50
38      1272450      1299097    241765.50          318112.50
39     21053472     21059649   4000159.68         5263368.00
40     22608040     22634699   4295527.60         5652010.00
41     44425744     44456319   8440891.36        11106436.00
42     26438142     26465912   5023246.98         6609535.50
43      6709200      6736319   1274748.00         1677300.00
44     48361012     48396512   9188592.28        12090253.00
45     18961236     19018081   3602634.84         4740309.00
46     20309265     20368392   3858760.35         5077316.25
47     52838958     52888220  10039402.02        13209739.50
48     26580424     26617617   5050280.56         6645106.00
49     36698701     36714727   6972753.19         9174675.25
50      4432978      4453652    842265.82         1108244.50
51     44779740     44834910   8508150.60        11194935.00
52      1111532      1156626    211191.08          277883.00
53     32289985     32321964   6135097.15         8072496.25
54      1945194      2003596    369586.86          486298.50
55     68440575     68492194  13003709.25        17110143.75
56     10638790     10687102   2021370.10         2659697.50
57     83835940     83876143  15928828.60        20958985.00
58     74328736     74341040  14122459.84        18582184.00
59       870026       905905    165304.94          217506.50

    Perdida_Estimada  Porcentaje_Ventas
0          7000.0000           0.807117
1           600.0000           0.069181
2           600.0000           0.069181
5          3300.0000           0.380498
6         41077.8830           4.736378
7         17426.8315           2.009355
8         39116.5410           4.510231
9          7879.0005           0.908468
10        23091.6900           2.662527
11         1856.7865           0.214092
12        27478.5720           3.168345
13        29469.6540           3.397921
14        12519.2305           1.443497
15        17448.5630           2.011861
16        12120.1380           1.397481
17         1170.2610           0.134934
18        15906.8460           1.834097
19        17846.9610           2.057797
20        27127.5455           3.127871
21        31233.1025           3.601251
22        24834.6480           2.863494
23        25318.1800           2.919247
24        25138.6350           2.898545
25        22269.9610           2.567780
26        21374.3040           2.464508
27         4918.6560           0.567133
28         1149.6000           0.132552
29          500.6990           0.057732
30        14585.9105           1.681790
31        12604.4040           1.453318
32        18202.9500           2.098844
33        12445.4880           1.434994
34         8322.7230           0.959630
35          894.7670           0.103169
36         6120.8805           0.705752
37         7393.2390           0.852458
38          636.2250           0.073358
39        10526.7360           1.213758
40        11304.0200           1.303381
41        22212.8720           2.561197
42        13219.0710           1.524190
43         3354.6000           0.386793
44        24180.5060           2.788070
45         9480.6180           1.093138
46        10154.6325           1.170853
47        26419.4790           3.046229
48        13290.2120           1.532393
49        18349.3505           2.115724
50         2216.4890           0.255566
51        22389.8700           2.581605
52          555.7660           0.064081
53        16144.9925           1.861556
54          972.5970           0.112143
55        34220.2875           3.945681
56         5319.3950           0.613339
57        41917.9700           4.833242
58        37164.3680           4.285140
59          435.0130           0.050158

In [24]:
ordenado = df.sort_values(by="Total_Venta", ascending=False)

print(ordenado)

                Producto   Precio  Cantidad  Costo_Envio   Categoria  \
57          Kit Domótica  4191797        20        40203  Tecnología
6              Impresora  3734353        22        37566  Tecnología
8             Smartphone  4601946        17        36279  Tecnología
58          Raspberry Pi  4645546        16        12304  Tecnología
55    Sensor Inteligente  2737623        25        51619  Tecnología
21       Fuente de Poder  3287695        19        50398  Tecnología
13                   SSD  3274406        18        38406  Tecnología
12            Disco Duro  4579762        12        47963  Tecnología
20            Placa Base  2358917        23        49580  Tecnología
47     Capturadora Video  3108174        17        49262  Tecnología
23        Ventilador RGB  2531818        20        44097  Tecnología
24            Smartwatch  3351818        15        36903  Tecnología
22              Gabinete  4139108        12         9989  Tecnología
44       Pantalla Táctil  3454358        14        35500  Tecnología
10    Parlante Bluetooth  2309169        20         6890  Tecnología
51              Apple TV  2238987        20        55170  Tecnología
25             Proyector  3181423        14        21788  Tecnología
41                   NAS  4038704        11        30575  Tecnología
26               Escáner  2035648        21        13998  Tecnología
49  Cargador Inalámbrico  2822977        13        16026  Tecnología
32              Servidor  4045100         9        59916  Tecnología
19            Procesador  3244902        11        27816  Tecnología
15                Router  3172466        11        10913  Tecnología
7                 Tablet  2681051        13        53949  Tecnología
53            Alexa Echo  4612855         7        31979  Tecnología
18       Tarjeta Gráfica  1383204        23        33741  Tecnología
30                   UPS  1535359        19        23322  Tecnología
48               Hub USB  3322553         8        37193  Tecnología
42          Impresora 3D  4406357         6        27770  Tecnología
31  Regulador de Voltaje  2100734        12        21973  Tecnología
14           Memoria USB  3576923         7        22243  Tecnología
33       Docking Station  2765664         9        47794  Tecnología
16         Switch de Red  4040046         6        29113  Tecnología
40               Mini PC  1614860        14        26659  Tecnología
39            VR Headset   956976        22         6177  Tecnología
46           Mouse Gamer  2256585         9        59127  Tecnología
45      Teclado Mecánico   902916        21        56845  Tecnología
34     Lector Biométrico  1849494         9        47698  Tecnología
9            Auriculares  1750889         9        38481  Tecnología
37       Lámpara LED USB  2112354         7        30643  Tecnología
0                 Laptop  3500000         4        50000  Tecnología
36           Silla Gamer   582941        21        53321  Tecnología
56      Cámara Seguridad  1063879        10        48312  Tecnología
27            Cable HDMI  1229664         8        51274  Tecnología
43               Plotter  1341840         5        27119  Tecnología
5                Monitor  1100000         6        35000  Tecnología
50            Power Bank   402998        11        20674  Tecnología
11            Cámara Web  3713573         1        13865  Tecnología
4             Escritorio   900000         3        40000     Oficina
17             Micrófono   130029        18        14935  Tecnología
28             Cable USB   229920        10        23770  Tecnología
3                  Silla   450000         5        30000     Oficina
54           Google Nest   648398         3        58402  Tecnología
35         Control Gamer  1789534         1        16205  Tecnología
38                 Drone  1272450         1        26647  Tecnología
1                  Mouse    80000        15        10000  Tecnología
2                Teclado   120000        10        12000  Tecnología
52            Chromecast   277883         4        45094  Tecnología
29        Adaptador WiFi   500699         2        29964  Tecnología
59           Arduino Kit   870026         1        35879  Tecnología

    Total_Venta  Costo_Total          IVA  Ganancia_Estimada  \
57     83835940     83876143  15928828.60        20958985.00
6      82155766     82193332  15609595.54        20538941.50
8      78233082     78269361  14864285.58        19558270.50
58     74328736     74341040  14122459.84        18582184.00
55     68440575     68492194  13003709.25        17110143.75
21     62466205     62516603  11868578.95        15616551.25
13     58939308     58977714  11198468.52        14734827.00
12     54957144     55005107  10441857.36        13739286.00
20     54255091     54304671  10308467.29        13563772.75
47     52838958     52888220  10039402.02        13209739.50
23     50636360     50680457   9620908.40        12659090.00
24     50277270     50314173   9552681.30        12569317.50
22     49669296     49679285   9437166.24        12417324.00
44     48361012     48396512   9188592.28        12090253.00
10     46183380     46190270   8774842.20        11545845.00
51     44779740     44834910   8508150.60        11194935.00
25     44539922     44561710   8462585.18        11134980.50
41     44425744     44456319   8440891.36        11106436.00
26     42748608     42762606   8122235.52        10687152.00
49     36698701     36714727   6972753.19         9174675.25
32     36405900     36465816   6917121.00         9101475.00
19     35693922     35721738   6781845.18         8923480.50
15     34897126     34908039   6630453.94         8724281.50
7      34853663     34907612   6622195.97         8713415.75
53     32289985     32321964   6135097.15         8072496.25
18     31813692     31847433   6044601.48         7953423.00
30     29171821     29195143   5542645.99         7292955.25
48     26580424     26617617   5050280.56         6645106.00
42     26438142     26465912   5023246.98         6609535.50
31     25208808     25230781   4789673.52         6302202.00
14     25038461     25060704   4757307.59         6259615.25
33     24890976     24938770   4729285.44         6222744.00
16     24240276     24269389   4605652.44         6060069.00
40     22608040     22634699   4295527.60         5652010.00
39     21053472     21059649   4000159.68         5263368.00
46     20309265     20368392   3858760.35         5077316.25
45     18961236     19018081   3602634.84         4740309.00
34     16645446     16693144   3162634.74         4161361.50
9      15758001     15796482   2994020.19         3939500.25
37     14786478     14817121   2809430.82         3696619.50
0      14000000     14050000   2660000.00         3500000.00
36     12241761     12295082   2325934.59         3060440.25
56     10638790     10687102   2021370.10         2659697.50
27      9837312      9888586   1869089.28         2459328.00
43      6709200      6736319   1274748.00         1677300.00
5       6600000      6635000   1254000.00         1650000.00
50      4432978      4453652    842265.82         1108244.50
11      3713573      3727438    705578.87          928393.25
4       2700000      2740000    513000.00          675000.00
17      2340522      2355457    444699.18          585130.50
28      2299200      2322970    436848.00          574800.00
3       2250000      2280000    427500.00          562500.00
54      1945194      2003596    369586.86          486298.50
35      1789534      1805739    340011.46          447383.50
38      1272450      1299097    241765.50          318112.50
1       1200000      1210000    228000.00          300000.00
2       1200000      1212000    228000.00          300000.00
52      1111532      1156626    211191.08          277883.00
29      1001398      1031362    190265.62          250349.50
59       870026       905905    165304.94          217506.50

    Perdida_Estimada  Porcentaje_Ventas
57        41917.9700           4.833242
6         41077.8830           4.736378
8         39116.5410           4.510231
58        37164.3680           4.285140
55        34220.2875           3.945681
21        31233.1025           3.601251
13        29469.6540           3.397921
12        27478.5720           3.168345
20        27127.5455           3.127871
47        26419.4790           3.046229
23        25318.1800           2.919247
24        25138.6350           2.898545
22        24834.6480           2.863494
44        24180.5060           2.788070
10        23091.6900           2.662527
51        22389.8700           2.581605
25        22269.9610           2.567780
41        22212.8720           2.561197
26        21374.3040           2.464508
49        18349.3505           2.115724
32        18202.9500           2.098844
19        17846.9610           2.057797
15        17448.5630           2.011861
7         17426.8315           2.009355
53        16144.9925           1.861556
18        15906.8460           1.834097
30        14585.9105           1.681790
48        13290.2120           1.532393
42        13219.0710           1.524190
31        12604.4040           1.453318
14        12519.2305           1.443497
33        12445.4880           1.434994
16        12120.1380           1.397481
40        11304.0200           1.303381
39        10526.7360           1.213758
46        10154.6325           1.170853
45         9480.6180           1.093138
34         8322.7230           0.959630
9          7879.0005           0.908468
37         7393.2390           0.852458
0          7000.0000           0.807117
36         6120.8805           0.705752
56         5319.3950           0.613339
27         4918.6560           0.567133
43         3354.6000           0.386793
5          3300.0000           0.380498
50         2216.4890           0.255566
11         1856.7865           0.214092
4          1350.0000           0.155658
17         1170.2610           0.134934
28         1149.6000           0.132552
3          1125.0000           0.129715
54          972.5970           0.112143
35          894.7670           0.103169
38          636.2250           0.073358
1           600.0000           0.069181
2           600.0000           0.069181
52          555.7660           0.064081
29          500.6990           0.057732
59          435.0130           0.050158

In [25]:
# Exportar DataFrame final
df.to_excel("resultado_final.xlsx", index=False)

print("Archivo exportado correctamente")

Archivo exportado correctamente